### ISSUE TITLE
00 -- JEN HAMILTON

### ISSUE THREAD

**Issue by embryoconcepts** [TheIronYard--Orlando/2015--FALL--ROR#1]
- [X] [Create a Github account](https://github.com/signup)
- [x] _5 min_ [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so I can recognize your face.
  - [x] Your full name, so I can recognize your name.
  - [x] A valid public email address, so I can contact you if I need to.
- [x] [Star the class repo](https://github.com/TheIronYard--Orlando/2015--FALL--ROR)
- [x] _10 min_ Read over [the class wiki](https://github.com/TheIronYard--Orlando/2015--FALL--ROR/wiki)
- [x] _10 min_ Read the `README.md` files in:
  - [x] [Assignments](https://github.com/TheIronYard--Orlando/2015--FALL--ROR/tree/master/Assignments)
  - [x] [Notes](https://github.com/TheIronYard--Orlando/2015--FALL--ROR/tree/master/Notes)
- [x] _5 min_ [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--FALL--ROR/issues/new)
  - [x] Named `00 -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] With this checklist as the description
- GIT 'ER DONE
  - [Git Basics course at Treehouse](http://teamtreehouse.com/library/git-basics) (optional)
  - [`git` path at CodeSchool](https://www.codeschool.com/paths/git) (optional)
  - [x] _20 min_ Complete the CodeSchool short course, [Try Git](https://www.codeschool.com/courses/try-git)
  - [x] _10 min_ [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
    - [x] Add a link to your new Github repo as a comment in your WIP Issue.
- COMMAND LINE FU
  - [x] _5 min_ Read http://eddywashere.com/blog/an-intro-to-the-os-x-command-line/
  - [x] _30 min_ Complete https://www.codecademy.com/courses/learn-the-command-line/
  - [Do It The Hard Way](http://cli.learncodethehardway.org/book/) (optional)
- [x] _15 min_ [Install Homebrew](http://brew.sh) on your Mac
  - [x] Open `Terminal.app`
  - [x] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [x] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
- [x] _10 min_ Using the `brew` command, install the following packages:
  - [x] `zsh`
  - [x] `git`
  - [x] `hub`
  - [x] `chruby`
  - [x] `ruby-install`
- [x] _10 min_ Using the `ruby-install` command, install Ruby 2.2.3.
- [x] _5 min_ Set the default version of Ruby to 2.2.3.
- [x] _10 min_ Add the output of the following commands as comments on your _WIP Issue_:
  - [x] `which zsh && zsh --version`
  - [x] `which git && git --version`
  - [x] `which hub && hub --version`
  - [x] `which ruby && ruby -v`
- [x] _10 min_ [Install Caskroom](http://caskroom.io)
- [x] _5 min_ Using `brew cask`, install the following applications:
  - [x] [Google Chrome](http://google.com/chrome)
  - [x] [Sublime Text](http://sublimetext.com)
  - [x] [Slack](http://www.slack.com)
  - [x] [Flux](http://www.justgetflux.com)
- NOTE: The above looks like a lot, but those tasks go quickly. The following items require, and deserve, more time. Don't put them off!  
- [x] _5 min_ [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
  - [x] Add a link to your `Fork-and-Spoon` repo as a comment on your _WIP Issue_
- [x] _20 min_ Install Prezto
  - [x] Find _and fork_ the Prezto project on Github; add a link as a comment on your _WIP Issue_
  - [x] Use the `hub` command to clone your fork into your home directory as `.zprezto`: 
    `hub clone prezto ~/.zprezto`
  - [x] Follow the installation instructions in the `README.md` file
- [x] _20 min_ Read the first four pages about growth vs fixed mindsets at http://mindsetonline.com/whatisit/about/index.html. I'll be honest, this sounded hokey to me when I first read it, but watching how people with the two mindsets performed in previous cohorts, I'm sold on the idea. You have much more control over how much you can learn than you might think.
- [x] _5 hr_ Read the book [Learn to Program](https://pine.fm/LearnToProgram/). 
  - [x] 0. Getting Started
  - [x] 1. Numbers
  - [x] 2. Letters
  - [x] 3. Variables and Assignment
  - [x] 4. Mixing It Up
  - [x] 5. More About Methods
  - [x] 6. Flow Control
  - [x] 7. Arrays and Iterators
  - [x] 8. Writing Your Own Methods
  - [x] 9. Classes
  - [x] 10. Blocks and Procs
  - [x] 11. Beyond This Tutorial
- [x] **Pause and Reflect**
  - [x] Answer question 1 in a comment on your WIP Issue.
  - [x] Answer question 2 in a comment on your WIP Issue.

**Comment by embryoconcepts** [comment]
- which zsh && zsh --version
  - /usr/local/bin/zsh
  - zsh 5.1 (x86_64-apple-darwin14.5.0)
- which git && git --version
  - /usr/local/bin/git
  - git version 1.8.4
- which hub && hub --version
  - /usr/local/bin/hub
  - git version 1.8.4
  - hub version 1.10.6
- which ruby && ruby -v
  - /Users/jenhamilton/.rubies/ruby-2.2.3/bin/ruby
  - ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

**Comment by embryoconcepts** [comment]
Github's Hello World tutorial repo: https://github.com/embryoconcepts/hello-world

**Comment by embryoconcepts** [comment]
forked Fork and Spoon repo: https://github.com/embryoconcepts/Spoon-Knife

**Comment by embryoconcepts** [comment]
Forked Prezto repo: https://github.com/embryoconcepts/prezto

**Comment by embryoconcepts** [comment]
Command `hub clone prezto ~/.zprezto` did not work to clone. Followed Prezto README directions, have lost all previous prompt modifications, aliases and syntax highlighting. Also getting this error: `/etc/zprofile:source:2: not enough arguments`. 'prompt' command to preview themes is not found.

**Comment by bgates** [comment]
Hi @embryoconcepts. I'm not getting the email updates when comments are left in these issues; I must have turned off a setting somewhere in GitHub. Now that I know you're here, let's figure out this prezto problem. 
I just ran `hub clone prezto ~/try_to_replicate_error/.zprezto` and it worked, though I was asked for a password for an rsa key I had generated first. It sounds like you got past the hub issue though and the pressing problem is getting your terminal straightened out. You probably found [this report of the same error message](https://github.com/robbyrussell/oh-my-zsh/issues/2162), and if not that's the first thing I suggest trying. 

I also turned up [this](https://github.com/sorin-ionescu/prezto/issues/231) which suggests (a) the problem may have come about because you already had a ~/.zshrc, (b) other Iron Yard students have had this problem and gotten past it, and unfortunately (c) the originator of Prezto can be kind of an ass.

The stuff you're not seeing in the terminal is still there in your ~/.bashrc (or maybe ~/.bash_profile), so if prezto becomes too much of a headache you can revert to bash. I don't think that will be necessary, but it's nice to have a fallback. I expect you can copy the aliases from your ~/.bash**\* to ~/.zshrc, because those aren't shell-dependent. Syntax highlighting and prompt mods might be trickier; could I take a look at your dotfiles and see what they're doing?

**Comment by embryoconcepts** [comment]
@bgates I did see the first link you mention, as well as some others, but nothing helped. I'll take a look at the second when I get home. If I can get it to work, it may be better than what I've put together for bash. If not, can we find some time for you to take a look?

**Comment by bgates** [comment]
Certainly. My schedule is pretty open, aside from an appointment in Winter Park Friday afternoon at 1, so you can suggest a time.

**Comment by embryoconcepts** [comment]
I finally got Prezto to work (uninstalled, deleted all .z\* files, reinstalled. The first time you open zsh, it creates a blank .zshrc file, so you have to delete that again, before installing Prezto) There are some tweaks that I'd like to have working in zsh, like git-completion.bash, and some prompt modifications. Can/would you take a look? I have time today, if you do. Let me know what works best.

**Comment by embryoconcepts** [comment]
Never mind - I think I have it all resolved!

**Comment by embryoconcepts** [comment]
_What difficulties do you predict that you will encounter during our course? How have you reacted to similar situations in the past? How do you plan on reacting to these situations during the class?_

My main concerns are informed by previous experiences with CS education: having enough time to absorb the materials and complete assignments; maintaining my energy levels, over-thinking problems (and getting stuck in a research black hole); scope creep for final project, having enough time to network; and finally, getting a job. The difference in this upcoming experience is that I will be focused only school, not having to juggle a more-than full time job alongside.  Because it's such a focused, immersive program, it will likely be just as intense, but not having to switch mental gears will help.

As soon as I was accepted and enrolled, I started getting ready for TIY. Eating and sleeping well are essential for maintaining energy and focus. Lists help me stay on track, and keep projects from becoming overwhelming. Tackling assignments as soon as we get them prevents the procrastination blues. I've already started thinking about possible final projects, and ways to slim them down to the essential elements. The job hunting/networking is a big stressor for me, but I've already decided that I need to take the time to try and hit up one Meetup a week. All in all, I've tried to set up systems in my personal life to support this endeavor, and have trusted methods for staying focused and breaking problems down into bite-sized pieces. Finally, we have TIY instructors, mentors and other students for feedback when we need an outside perspective or advice.

**Comment by embryoconcepts** [comment]
_Which part of the prework did you like the MOST? Which part of the prework did you like the LEAST? If you found any of the prework confusing, please explain._

My most/least like element was the same thing - Prezto. It was a pain to figure out the install problems (thanks @bgates!), and I didn't like the idea of losing hours of work that I'd done on my bashprofile. BUT! Once it was installed and I'd done some tweaking, I realized that it was much more powerful and customizable that what I had cobbled together before, and less likely to cause strange errors. After reading more about zsh v. bash, I also see the benefits of switching over to zsh. I was already familiar with everything except Caskroom, but went through all the tutorials again to refresh. It was a little tedious to do again, but people rarely retain 100% the first time through, so it's worth reviewing. Also, I've done very few Issues and Pull Requests, so practice is super helpful. I'd like to learn more about SSH, if we can put in requests:)

**Comment by bgates** [comment]
Outstanding, @embryoconcepts! Everything I can see in how you've handled this pre-class assignment - your willingness to take a second look at things you've seen before and wrestle with things you haven't, reaching out when you got stuck and working through issues on your own, conducting independent research beyond the scope of the assignment, having a plan to stay focused during the course from each individual assignment to final project and job search, and of course chewing through all of these check boxes within the first few days after the assignment was released - tells me you are going to thrive here. It's going to be an invaluable asset to the rest of the students to have your experience and attitude in the class. 

Requests are welcome, pull- or otherwise. I have one for you: Could you let me know a few of your non-programming interests? I like to keep the apps that we build connected in some way to subjects students have an interest in. Once you give me a couple of those, you can close this issue!

**Comment by embryoconcepts** [comment]
Thanks for the kind words! As for outside interests, here's a sample: 
- Organizing/productivity/efficiency life hacks
- Automating everyday tasks
- Cooking
- Pets/pet rescue
- Books/reading
- Activism 
- Pool (as in the table sport)
